/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f4f4ef",
        "on-primary": "#e2fff9",
        "surface-bright": "#faf9f5",
        "on-primary-fixed-variant": "#39635c",
        "on-error": "#fff7f6",
        "on-background": "#30332f",
        "tertiary-fixed": "#fde7d3",
        "on-secondary-fixed-variant": "#4b5f63",
        "outline": "#797b76",
        "on-tertiary-fixed-variant": "#6d5e4f",
        "error-container": "#fa746f",
        "on-primary-fixed": "#1b4640",
        "surface-container-highest": "#e1e3dd",
        "secondary-dim": "#43565a",
        "surface-container-high": "#e8e9e3",
        "on-tertiary-fixed": "#504234",
        "on-secondary-container": "#415559",
        "tertiary-container": "#fde7d3",
        "tertiary": "#6c5c4d",
        "primary-fixed-dim": "#b1ddd5",
        "on-surface-variant": "#5d605b",
        "on-tertiary-container": "#635445",
        "surface-tint": "#3d6660",
        "inverse-on-surface": "#9d9d9a",
        "surface-container": "#eeeee9",
        "inverse-primary": "#cdfaf1",
        "surface": "#faf9f5",
        "error": "#a83836",
        "primary-fixed": "#bfebe3",
        "surface-variant": "#e1e3dd",
        "on-primary-container": "#2f5953",
        "secondary-fixed": "#d1e6eb",
        "surface-dim": "#d9dbd4",
        "inverse-surface": "#0d0f0d",
        "secondary-container": "#d1e6eb",
        "primary-container": "#bfebe3",
        "tertiary-fixed-dim": "#eed9c6",
        "secondary": "#4e6266",
        "tertiary-dim": "#5f5142",
        "primary-dim": "#315a54",
        "primary": "#3d6660",
        "background": "#faf9f5",
        "secondary-fixed-dim": "#c3d8dc",
        "on-secondary-fixed": "#2f4346",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#b0b3ad",
        "on-error-container": "#6e0a12",
        "error-dim": "#67040d",
        "on-secondary": "#ecfcff",
        "on-surface": "#30332f",
        "on-tertiary": "#fff7f3"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
}
